# H2 inMemory
# remote client: tcp://localhost:9092/mem:javaops

spring.jackson.serialization.indent_output: true

spring.datasource:
     url: jdbc:h2:mem:javaops
     username: sa
     password:

spring.jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties.hibernate.format_sql: true

logging.level:
#   org.thymeleaf: DEBUG
   org.springframework:
      security: DEBUG
      web: DEBUG
      data: DEBUG
      http.converter: DEBUG

app:
  activation-secret-salt: test
  cache-seconds: 1
  host-url: http://localhost:8080
  integration:
    vk-token: vk-token
    slack-tokens.topjava: dummy-slack-token-topjava
    slack-tokens.javaops: dummy-slack-token-javaops
  secret-key: secret

spring:
  mail.host: smtp.yandex.ru
  mail.port: 465
  mail.username: mail@yandex.ru
  mail.password: password
  mail.properties.mail.smtp.ssl.enable :  true
  mail.properties.mail.debug: false

