INSERT INTO USERS (FULL_NAME, EMAIL, GMAIL, PASSWORD) VALUES
  ('Григорий Кислин', 'gkislin@yandex.ru', NULL, '$2a$10$tgEdY6aPPUVdaHUTehckdOyCTc6DCAicSjZEF5X73aPMIZQc.dyV6'),
  ('User email','slash_ea@mail.ru', 'eugeneakhramovich@gmail.com', '$2a$10$tgEdY6aPPUVdaHUTehckdOyCTc6DCAicSjZEF5X73aPMIZQc.dyV6'),
  ('Java_Online_Projects', 'admin@javaops.ru', NULL, '$2a$10$tgEdY6aPPUVdaHUTehckdOyCTc6DCAicSjZEF5X73aPMIZQc.dyV6');

INSERT INTO PROJECT (NAME) VALUES ('topjava');

INSERT INTO GROUPS (NAME, TYPE, PROJECT_ID) VALUES
  ('test', null, null),
  ('topjava_register', 'REGISTERED', 1),
  ('topjava06', 'CURRENT', 1),
  ('topjava05', 'FINISHED', 1);


INSERT INTO USER_GROUP (USER_ID, GROUP_ID) VALUES (1, 4);

ALTER TABLE PUBLIC.USER_GROUP ALTER COLUMN TYPE RENAME TO REGISTER_TYPE;
ALTER TABLE PUBLIC.USER_GROUP ADD PARTICIPATION_TYPE VARCHAR(255) NULL;

ALTER TABLE USERS ADD STATS_AGREE BOOL DEFAULT FALSE;
UPDATE USERS SET STATS_AGREE=FALSE;